phases:
- phase: Linux
  variables:
    PYTHON_VERSION: 2.7
  queue:
    name: 'Hosted Linux Preview'
    parallel: 9
    demands:
    - agent.os -equals linux
    matrix:
      regular:
        TASK: regular
      mpi:
        TASK: mpi
        PYTHON_VERSION: 2.7
      pylint: 
        TASK: pylint
      doc:
        TASK: check-docs
      inference:
        TASK: if-else
      sdist:
        TASK: sdist
        PYTHON_VERSION: 3.4
      bdist:
        TASK: bdist
        PYTHON_VERSION: 3.5
      gpu_1:
        TASK: gpu 
        METHOD: source
      gpu_2:
        TASK: gpu 
        METHOD: pip
  steps:
  - script: bash .vsts-ci/setup.sh
  - task: CondaEnvironment@1
  inputs:
    #createCustomEnvironment: # Optional
    #environmentName: # Required when createCustomEnvironment == True
    packageSpecs: 'python=$(PYTHON_VERSION)' # Optional
    #updateConda: # Optional
    #installOptions: # Optional
    createOptions: '-q -n test-env'
    #cleanEnvironment: # Optional
  - script: bash .vsts-ci/test.sh 





